### ISSUE TITLE
Failed to start server. In GitHub Actions

### ISSUE THREAD

**Issue by Tygovanommen** [donatj/mock-webserver#52]
Writing and executing unit tests locally works fine with this library, but when executing it through Github actions it gives me the following error:
`donatj\MockWebServer\Exceptions\ServerException: Failed to start server. Is something already running on port 8080?`

I've tried multiple ports and even the dynamic port, but it does not work. Below the code I add to my unit test.

```
abstract class ApiTestCase extends TestCase {
	protected MockWebServer $server;

	protected function setUp(): void {
		$this->server = new MockWebServer();
		$this->server->start();

		$this->server->setResponseOfPath(
			'/' . AuthenticationApi::TOKEN_URI,
			new ResponseStack(
				new Response( $this->getAuthenticatedJson() )
			)
		);
	}
}
```

And my workflow yml file:

```
name: PHPUnit tests

on:
  push:
    branches:
      - development

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: sockets json

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-ansi

      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit tests --coverage-text
```
